#!/usr/bin/env bash

function indent() {
	c='s/^/       /'
	case $(uname) in
		Darwin) sed -l "$c";;
		*)      sed -u "$c";;
	esac
}

build_dir=$1
env_dir=$3
# Make sure the URL is escaped properly
original_url="$(cat $env_dir/ORIGINAL_REPO_URL)"
replacement_url="$(cat $env_dir/REPLACEMENT_REPO_URL)"
gemfiles="$(cat $env_dir/GEMFILES)"

if [ "$gemfiles" == "" ]; then
  gemfiles="Gemfile*"
fi


if [ "$original_url" == "" ]; then
	echo "-----> No original url specified"
elif [ "$replacement_url" == "" ]; then
	echo "-----> No replacement url specified"
else
  # Looping over all gemfiles
  echo "-----> Renaming $original_url to $replacement_url in $gemfiles"
  sed -i.bak "s/$original_url/$replacement_url/g" $build_dir/$gemfiles

	exit 0
fi
